<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUltimosPostsDiferentes($postsCargados)
    {
        $postsCargados = "('". implode( "', '" , $postsCargados ) . "' )";

        $em = $this->getEntityManager();
        $dql = "SELECT p,u,v FROM AppBundle:Post p JOIN p.usuario u JOIN p.videojuego v WHERE p NOT IN ".$postsCargados;
        $consulta = $em->createQuery($dql);
        //$consulta->setParameter('postsCargados', $postsCargados);
        $consulta->getMaxResults(5);

        return $consulta->getResult();
    }
}
