# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    firewalls: 
        frontend: 
            pattern: ^/* 
            provider: chain_provider
            anonymous: ~ 
            form_login: 
                login_path: usuario_login 
                check_path: usuario_login_check 
                default_target_path: /
                always_use_default_target_path: true
            logout: 
                path: usuario_logout

    access_control: 
        - { path: ^/usuarios/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/videojuegos/portada, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios/usuariocrud, roles: ROLE_ADMIN } 
        - { path: ^/usuarios/*, roles: [ROLE_USUARIO, ROLE_ADMIN] } 
        - { path: ^/videojuegos/*, roles: [ROLE_USUARIO, ROLE_ADMIN] } 
        - { path: ^/posts/*, roles: [ROLE_USUARIO, ROLE_ADMIN] }
        - { path: ^/comentarios/*, roles: [ROLE_USUARIO, ROLE_ADMIN] }
        - { path: ^/seguimientos/*, roles: [ROLE_USUARIO, ROLE_ADMIN] }  
        
    providers:
        chain_provider:
            chain:
                providers: [usuarios, administradores]
        usuarios: 
            entity: { class: AppBundle\Entity\Usuario, property: nombre }
        administradores: 
            memory: 
                users: 
                    admin: { password: '$2y$13$yJ4XcpZSyqZCL2LSvUd8CuVdxoTRg1Nzdpgx2kbVxE6wEdoYjoroK', roles: ['ROLE_ADMIN'] }

    role_hierarchy: 
        #ROLE_ADMIN: [ROLE_USUARIO]
    
    encoders: 
        AppBundle\Entity\Usuario: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
