usuariocrud_index:
    path:     /
    defaults: { _controller: "AppBundle:Usuario:index" }
    methods:  GET

usuariocrud_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Usuario:show" }
    methods:  GET

usuariocrud_new:
    path:     /new
    defaults: { _controller: "AppBundle:Usuario:new" }
    methods:  [GET, POST]

usuariocrud_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Usuario:edit" }
    methods:  [GET, POST]

usuariocrud_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Usuario:delete" }
    methods:  DELETE
