<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIeuxwii\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIeuxwii/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIeuxwii.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIeuxwii\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIeuxwii\appDevDebugProjectContainer([
    'container.build_hash' => 'Ieuxwii',
    'container.build_id' => 'afa8fd2f',
    'container.build_time' => 1588762597,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIeuxwii');
